### ISSUE TITLE
get all locations

### ISSUE THREAD

**Issue by rugvedz** [philipperemy/expressvpn-python#10]
Right now I'm only able to connect to the recommended locations. How can I get the list of all the possible locations available on Expressvpn?

**Comment by philipperemy** [comment]
@rugvedz which function/command (python or bash) or you using?

**Comment by rugvedz** [comment]
using change_ip in python

**Comment by philipperemy** [comment]
https://github.com/philipperemy/expressvpn-python/blob/9e403a04193945acf997e28ff66bf7498396802d/expressvpn/wrapper.py#L100

Just change this line to 
```python
vpn_list = run_command(VPN_LIST)
```

**Comment by rugvedz** [comment]
Tried doing that but it didn't work. I'm only able to connect to recommended locations shown on the desktop app using both change_ip and connect functions.

**Comment by philipperemy** [comment]
Humm then not sure how to do it. How many locations do you see in recommended?

**Comment by rugvedz** [comment]
I'm seeing 10 locations

**Comment by philipperemy** [comment]
That's weird. I don't have expressVPN at the moment so I can't really check why..

**Comment by rugvedz** [comment]
It would be amazing if you could please look into it. This package is really usefull and I was hoping to continue using it.

**Comment by philipperemy** [comment]
@rugvedz Thanks :) if you can generate me a key, I can have a look at it. Then you can disable it after I'm done

**Comment by KybraNET** [comment]
I will fork it now and have a look because i need that too

**Comment by philipperemy** [comment]
@REficul-dRAw thanks! I don't have an API key anymore so I can't really help but if you can have this sorted out it would be awesome!

**Comment by KybraNET** [comment]
Was easy:relaxed:  Feel free to have a look 6a64fde0ad294bc6d6f59e8db86bf50307afd3e6

**Comment by philipperemy** [comment]
Awesome! Open a PR once it's ready :)

**Comment by KybraNET** [comment]
Mate i will put flags to it later and after that you can merge to main if you want to :)

**Comment by philipperemy** [comment]
Okay sounds good!!

**Comment by philipperemy** [comment]
Pushed in V1.2. https://github.com/philipperemy/expressvpn-python/commit/7523d0c2bd4775da44f58cc59001a84c13db9f08
