### ISSUE TITLE
BannedException question

### ISSUE THREAD

**Issue by shaansharma1980** [philipperemy/expressvpn-python#11]
Where is the BannedExeption located, cant seem to import it ? How do I import it ?

**Comment by philipperemy** [comment]
@shaansharma1980 That's something you have to define and throw when you think the platform banned your IP.

**Comment by philipperemy** [comment]
```python
class BannedException(Exception):
    pass
```

```python
def scrape():
    # do stuff.
    # oh I was banned.
    raise BannedException()
```

**Comment by philipperemy** [comment]
Got added to the snippet in the README https://github.com/philipperemy/expressvpn-python#ip-auto-switching
