### ISSUE TITLE
can't install on termux

### ISSUE THREAD

**Issue by Enigma3000** [philipperemy/expressvpn-python#12]
Hi, is there a way to install expressvpn on termux?

I tried to execute the amd64.deb but it gives me this error:

**package architecture (amd64) does not match system (aarch64)**

thank you!!

**Comment by philipperemy** [comment]
@Enigma3000 not possible as ExpressVPN does not provide any package for termux.

**Comment by Enigma3000** [comment]
Thank you for the reply. I'll ask them to compile it for the correct architecture. Shouldn't be a problem for them.

**Comment by philipperemy** [comment]
Let me know!
