### ISSUE TITLE
Reconnect to specific server

### ISSUE THREAD

**Issue by ClemLanoe** [philipperemy/expressvpn-python#13]
I would like to reuse specific server IPs for different accounts on a website that I scrape. It would look odd for the accounts to always have changing IPs. The IPs must be UK-based. Is there a way to connect to a specific server so that I can fixed an IP for each account I scrape with?

**Comment by philipperemy** [comment]
@ClemLanoe I think aliases are what you're looking for.

https://github.com/philipperemy/expressvpn-python#connect-with-alias

You can list them with `expressvpn list all`. You will probably see a list like [`usa1`, `usa2`,...,`united-kingdom-1`, `united-kingdom-2`]

I don't have an expressVPN subscription at the moment so I can't test but ExpressVPN has a lot of servers in the UK from what I can remember.
