### ISSUE TITLE
How to choose a completely random server, regardless of speed?

### ISSUE THREAD

**Issue by sinkingfeeling** [philipperemy/expressvpn-python#18]
If I wanted to select a completely random server regardless of speed, would this be the proper way to modify vpn.sh?

`VPN_LOCATION=$(expressvpn list all | tail -n +4 | cut -d ' ' -f 1 | shuf | head -n 1)`

**Comment by philipperemy** [comment]
Yes just delete the `head -n 20`. Looks correct.
