### ISSUE TITLE
sudo pip install . # will install it as a package RETURN "You must give at least one requirement to install"

### ISSUE THREAD

**Issue by do-n-khanh** [philipperemy/expressvpn-python#2]
Hello, I am folloing your instruction to install expressvpn-python to ubuntu 14:

git clone git@github.com:philipperemy/expressvpn-python.git evpn
cd evpn
sudo dpkg -i expressvpn_1.2.0_amd64.deb # will install the binaries provided by ExpressVPN
sudo pip install . # will install it as a package

I got an error when running "sudo pip install . # will install it as a package"

It says: "You must give at least one requirement to install"

How to solve it?

**Comment by philipperemy** [comment]
Are you familiar with python? You should probably use virtual environment if it does not work well:

```
virtualenv -p python3.6 venv
source venv/bin/activate
git clone git@github.com:philipperemy/expressvpn-python.git evpn
cd evpn
pip install .
```

**Comment by do-n-khanh** [comment]
thank you. i solved the problem.

**Comment by philipperemy** [comment]
Thank you!!
