### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by only1isus** [philipperemy/expressvpn-python#3]
Just so you know, I get an error whenever I try using the code as is. The issue is caused by this line, the amount of locations to choose from is set to 47 (sliced from whatever is returned from the 'expressvpn list' command) in my case however, the amount is less than 47, 12 in fact, hence the error.https://github.com/philipperemy/expressvpn-python/blob/e131d9577d1d6dd2e7a7d8e7932c182348403f58/expressvpn/wrapper.py#L78 

```
for vpn_item in vpn_list[3:]:
        try:
            alias = vpn_item.split()[0]
            aliases.append(alias)
        except IndexError:
            return aliases
        # print('Found alias -> {}'.format(alias))
    return aliases
```
should fix this :)

**Output before code fix**
![outofrange1](https://user-images.githubusercontent.com/39845591/67151644-97594a80-f28e-11e9-9ab8-aa6ee65723e3.png)

**Comment by philipperemy** [comment]
@only1isus oh wow thanks for your feedback! Going to change that :)

**Comment by philipperemy** [comment]
Merged. https://github.com/philipperemy/expressvpn-python/pull/4

Thanks for reporting!
