### ISSUE TITLE
Can this be implemented for Windows 10 as well

### ISSUE THREAD

**Issue by ayushxx7** [philipperemy/expressvpn-python#7]
Currently, I have prepared an automation script based on PyAutoGUI & ExpressVPN Windows App to connect to a specified country. It works as expected. However, I was wondering if I could just connect/disconnect to VPN using API. Hence, I ask, is it possible to implement this wrapper for Windows as well?

**Comment by philipperemy** [comment]
It's not possible at the moment. ExpressVPN does not provide a binary for windows. You have to use Linux to be able to use this library. However if you can control the ExpressVPN Windows App with PyAutoGUI, you could maybe expose some commands like `expressvpn connect` or `expressvpn disconnect`. And then you could adjust this library. This can potentially work but might require some work on your side.

**Comment by ayushxx7** [comment]
Can you take a look at [this Gist](https://gist.github.com/ayushxx7/0866eb4df97a938d3267a6187dfd5e4e)? This is what I am currently using for windows.

Note: The screenshots are based on ExpressVPN version 7.7.11 (1920x1080p resolution)

![vpn_connected](https://user-images.githubusercontent.com/16764027/116441613-38a36280-a86f-11eb-9448-cbaaa435019f.png)
[VPN Connected]

![vpn_disconnected](https://user-images.githubusercontent.com/16764027/116441623-3a6d2600-a86f-11eb-9b76-47eb340a7bec.png)
[VPN Disconnected]

![vpn_germany](https://user-images.githubusercontent.com/16764027/116441626-3a6d2600-a86f-11eb-9a03-416693751e6f.png)
[Country Germany]

![vpn_taiwan](https://user-images.githubusercontent.com/16764027/116441630-3b9e5300-a86f-11eb-86e0-c1b921cd95b5.png)
[Country Taiwan]

![vpn_location_selector](https://user-images.githubusercontent.com/16764027/116441627-3b05bc80-a86f-11eb-8ef0-6b39c0625ca4.png)
[Select Country Button]

Let me know if we can somehow collaborate on this project for integrating Windows.

**Comment by philipperemy** [comment]
@ayushxx7 it will be a bit difficult I don't have any windows machine...

**Comment by philipperemy** [comment]
But your code seems to be very well written. I think you're on the good way!!

**Comment by jochenboele** [comment]
Hi @ayushxx7 Did you manage to get it working?

**Comment by ayushxx7** [comment]
Hi @jochenboele. The handler works as expected. You can get the gist from [here](https://gist.github.com/ayushxx7/0866eb4df97a938d3267a6187dfd5e4e).
I am yet to figure out how I can integrate my script into @philipperemy's project.

**Comment by philipperemy** [comment]
@ayushxx7 wow your wrapper is pretty involved!

**Comment by thewh1teagle** [comment]
You can use this library I made - [Evpn](https://github.com/thewh1teagle/evpn)
Windows is supported

**Comment by philipperemy** [comment]
@thewh1teagle thank you!
