### ISSUE TITLE
Make random connection to more servers

### ISSUE THREAD

**Issue by jochenboele** [philipperemy/expressvpn-python#9]
Hi,
This script is very helpfull.
Would it be possible to add a parameter so you can run random_connect to more servers? Now I seem to be getting to the same +- 50 servers every time. I want to make use of as much as possible servers from ExpressVPN.

**Comment by philipperemy** [comment]
@jochenboele thank you!
Yes it's possible and easy.

https://github.com/philipperemy/expressvpn-python/blob/9e403a04193945acf997e28ff66bf7498396802d/vpn.sh#L20

Edit this line and change 20 to 50.
